POST http://localhost:3000/videos
Content-Type: application/json

{
    "title":"Video 003 node",
    "description":"esse é o primeiro video 01 ",
    "duration":180
}

###

GET http://localhost:3000/videos?search=node

###

PUT http://localhost:3000/videos/3c00551b-9859-4d08-9e65-67ba07d08303
Content-Type: application/json

{
    "title":"Video 003 node + 2",
    "description":"esse é o primeiro video 01",
    "duration":180
}

###
DELETE  http://localhost:3000/videos/3c00551b-9859-4d08-9e65-67ba07d08303s
